"""Update

Revision ID: e1875c8a3315
Revises: 6a2f3fd82b02
Create Date: 2024-08-22 16:32:34.828889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1875c8a3315'
down_revision: Union[str, None] = '6a2f3fd82b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_value', sa.Column('model_type', sa.String(length=255), nullable=True))
    op.drop_column('model_value', 'sensor_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_value', sa.Column('sensor_type', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('model_value', 'model_type')
    # ### end Alembic commands ###
