"""Create SensorValue

Revision ID: 4f1d209636e2
Revises: 124c5e40042d
Create Date: 2024-07-21 11:45:53.295638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4f1d209636e2'
down_revision: Union[str, None] = '124c5e40042d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_value',
                    sa.Column('sensor_type', sa.String(length=255), nullable=True),
                    sa.Column('field', sa.String(length=128), nullable=True),
                    sa.Column('value', sa.String(length=64), nullable=True),
                    sa.Column('measurement', sa.String(length=64), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_value'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_value')
    # ### end Alembic commands ###
