"""Add name in Scenario

Revision ID: 70c2d585deaa
Revises: 18c347fb5c5a
Create Date: 2024-08-01 19:42:53.053484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c2d585deaa'
down_revision: Union[str, None] = '18c347fb5c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'name')
    # ### end Alembic commands ###
