"""Add eng names variable accident

Revision ID: e447a5c5e750
Revises: 8ab2810b9ee5
Create Date: 2024-09-03 18:56:42.128281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e447a5c5e750'
down_revision: Union[str, None] = '8ab2810b9ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accident', sa.Column('param_mapping_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accident', 'param_mapping_names')
    # ### end Alembic commands ###
