"""Add status Location

Revision ID: 18c347fb5c5a
Revises: 4570df9ae491
Create Date: 2024-08-01 19:40:24.502425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c347fb5c5a'
down_revision: Union[str, None] = '4570df9ae491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('status', sa.Enum('DEVELOPING', 'INACTIVE', 'COMPLETED', name='locationstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'status')
    # ### end Alembic commands ###
