"""Database Modify Declarative

Revision ID: 58d8eb8bd151
Revises: e42fa3d3a292
Create Date: 2024-07-04 22:50:25.058959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d8eb8bd151'
down_revision: Union[str, None] = 'e42fa3d3a292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
