"""Add name Scenario

Revision ID: 0985e76094b1
Revises: 7d61cdbbeae4
Create Date: 2024-07-31 18:18:11.237431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0985e76094b1'
down_revision: Union[str, None] = '7d61cdbbeae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario', 'name')
    # ### end Alembic commands ###
