"""Add eng names variable

Revision ID: 145ad271de36
Revises: e1875c8a3315
Create Date: 2024-09-02 21:37:22.606295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145ad271de36'
down_revision: Union[str, None] = 'e1875c8a3315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('param_mapping_names', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'param_mapping_names')
    # ### end Alembic commands ###
